# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8083

# Spring配置
spring:
  application:
    name: skyblue-blog-system
  # 控制台打印输出 启动颜色格式化
  output:
    ansi:
      enabled: always
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # Spring data Jpa
  jpa:
    show-sql: true
    open-in-view: false
  #  hibernate:   自动建表
  #    ddl-auto: update
  # redis 配置
  redis:
    # 地址
    host: 192.168.80.10
    # 端口，默认为6379
    port: 6379
    # 密码
    password: master
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
  # 邮件 配置
  mail:
    host: smtp.163.com
    username: codeprobe@163.com
    password: XVPKIKHNOAGOMNQD
    protocol: smtp
    nickname: 蔚蓝博客
  # solr 配置
  data:
    redis:
      repositories:
        enabled: false
    solr:
      repositories:
        enabled: false
      # 地址:端口
      host: http://192.168.80.10:8983/solr/blog_system_core

# log
logging:
  config: classpath:logback-spring.xml
  level:
    dao: debug

# image upload
blog.image.store-path: D:\WorkSpace\blog\images
# max-size
blog.image.max-size: 2097152

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true

